import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ConvexClerkProvider from './components/client/ConvexClerkProvider';
import { ClerkProvider } from '@clerk/nextjs/app-beta';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} >
      <ConvexClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            {children}
          </body>
        </html>
      </ConvexClerkProvider>
    </ClerkProvider>
  )
}
